/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    CloseIcon: typeof import('./src/components/ui/CloseIcon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Lighbox: typeof import('./src/components/Lighbox.vue')['default']
    MinusIcon: typeof import('./src/components/ui/MinusIcon.vue')['default']
    NextIcon: typeof import('./src/components/ui/NextIcon.vue')['default']
    PlusIcon: typeof import('./src/components/ui/PlusIcon.vue')['default']
    PreviousIcon: typeof import('./src/components/ui/PreviousIcon.vue')['default']
    ProductDescription: typeof import('./src/components/ProductDescription.vue')['default']
    ProductSlider: typeof import('./src/components/ProductSlider.vue')['default']
    ProductsView: typeof import('./src/components/ProductsView.vue')['default']
  }
}
